import { GameDefinition, GameKey, RoomRules } from '@/types/game';

/** Every game the lobby offers. `live` games run on cardroom-server; the rest are offline demos. */
export const GAME_DEFINITIONS: Record<GameKey, GameDefinition> = {
  high_card: {
    key: 'high_card',
    icon: 'A♠',
    name: 'High Card',
    shortName: 'High Card (2–8P)',
    badge: '2–8 Players',
    playerCountLabel: '2–8 Players',
    playersCount: 2,
    suitGlyph: '♠',
    suitColor: 'text-slate-900',
    description: 'Everyone draws one card. Highest card takes the hand.',
    tag: 'Live · Server',
    rulesOverview:
      'Players draw one card each in seat order, 15 seconds per turn. Highest rank wins; a tied rank is broken by suit (♠ > ♥ > ♦ > ♣). Cards stay hidden from everyone else until the last player has drawn.',
    defaultCode: '',
    live: true,
  },
  hearts: {
    key: 'hearts',
    name: 'Hearts',
    shortName: 'Hearts (4P)',
    badge: '4 Players',
    playerCountLabel: '4 Players',
    playersCount: 4,
    suitGlyph: '♥',
    suitColor: 'text-red-600',
    description: 'Avoid ♠Q & ♥ penalty cards. Shoot the moon for 26 pts.',
    tag: 'Standard Rules',
    rulesOverview:
      'Goal is to avoid taking points: each Heart is 1 penalty pt, Queen of Spades (♠Q) is 13 pts. Taking all 26 points shoots the moon, giving 26 pts to each opponent instead!',
    defaultCode: 'HRT-8429',
    rule1: 'Omnibus (+10 Jack of Diamonds ♦)',
    rule2: 'Passing (Left · Right · Across · Hold)',
    rule3: 'Fast Game to 50 pts (Default 100)',
  },
  spades: {
    key: 'spades',
    name: 'Spades',
    shortName: 'Spades (4P - 2v2)',
    badge: '2v2 Teams',
    playerCountLabel: '4P',
    playersCount: 4,
    suitGlyph: '♠',
    suitColor: 'text-slate-950',
    description: 'Team trick-taking, Nil bids & strategic bag management.',
    tag: 'Partnership Bidding',
    rulesOverview:
      'Partners sit across each other. Each player bids the tricks they expect to win. Spades are always trump. Make exact bids to avoid bag penalties (-100 for 10 bags) or bid Blind Nil for high stakes!',
    defaultCode: 'SPD-3190',
    rule1: 'Blind Nil Bidding (+200 / -200 pts)',
    rule2: 'Bag Penalty Enabled (10 bags = -100)',
    rule3: 'First to 500 Points (or -200 loss)',
  },
  euchre: {
    key: 'euchre',
    name: 'Euchre',
    shortName: 'Euchre (4P - 2v2)',
    badge: '24-Card Deck',
    playerCountLabel: '4P',
    playersCount: 4,
    suitGlyph: '♦',
    suitColor: 'text-red-600',
    description: 'Fast-paced trump caller with Bowers and lone hand dashes.',
    tag: 'Trump Calling',
    rulesOverview:
      'Played with a 24-card deck (9 through Ace). Highest trump is the Jack of the trump suit (Right Bower), followed by the other Jack of same color (Left Bower). First team to 10 points wins.',
    defaultCode: 'ECH-5021',
    rule1: 'Stick the Dealer (forced call)',
    rule2: 'Canadian Loner rule enabled',
    rule3: 'Standard 10-point match',
  },
  oh_hell: {
    key: 'oh_hell',
    name: 'Oh Hell / Contract',
    shortName: 'Oh Hell (3-6P)',
    badge: 'Variable Hands',
    playerCountLabel: '3-6P',
    playersCount: 4,
    suitGlyph: '♣',
    suitColor: 'text-slate-950',
    description: 'Precision contracts where exact trick bidding scores big.',
    tag: 'Exact Contract Bidding',
    rulesOverview:
      'Each hand features an increasing or decreasing number of cards. Players must bid the exact number of tricks they will take. Only players who hit their exact contract earn bonus points.',
    defaultCode: 'OHL-7814',
    rule1: 'Strict Bidding (Total bids cannot equal hand)',
    rule2: 'Decreasing hand sizes (10 down to 1)',
    rule3: '10 pts + 1 per trick score format',
  },
  custom: {
    key: 'custom',
    name: 'Custom Deck / Sandbox',
    shortName: 'Custom Deck (2-8P)',
    badge: 'Freeform',
    playerCountLabel: '2-8P',
    playersCount: 4,
    suitGlyph: '🂠',
    suitColor: 'text-slate-950',
    description: 'Freeform table with customizable rules, custom chips & deck counts for house games.',
    tag: 'Sandbox Table',
    rulesOverview:
      'Freeform sandbox room with custom deck configurations, jokers, customizable dealing controls, private hands, and chips. Perfect for homebrew games or classic variants.',
    defaultCode: 'BOX-9912',
    rule1: 'Include Jokers (2 Cards)',
    rule2: 'Enable Table Poker Chips / Counters',
    rule3: 'Manual Dealer Rotation',
  },
};

/** Initial house-rule toggles per game, before the host changes any. */
export const DEFAULT_RULES: Record<GameKey, RoomRules> = {
  high_card: { rule1: false, rule2: false, rule3: false },
  hearts: { rule1: true, rule2: true, rule3: false },
  spades: { rule1: true, rule2: true, rule3: true },
  euchre: { rule1: true, rule2: false, rule3: true },
  oh_hell: { rule1: true, rule2: true, rule3: true },
  custom: { rule1: true, rule2: true, rule3: false },
};
